In [21]:
words = open('names.txt', 'r').read().splitlines()

In [22]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [23]:
len(words)

32033

In [24]:
max(len(w) for w in words)

15

In [25]:
import torch

In [26]:
# The rows of our tensor represent all the possible 2 character input that we can have -> n^2 with = alphabet + '.' 

N = torch.zeros((27**2,27), dtype=torch.int32)

In [27]:
#Building indexes for charaters
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [28]:
chars.insert(0, '.')

In [29]:
#Building a table for all the possible combinations of two characters 
stoiTri = {}
i = 0
for c1 in chars:
    for c2 in chars:
        stoiTri[c1+c2] = i
        i = i + 1
itosTri = {v:j for j,v in stoiTri.items()} 

In [68]:
#In this modelisation, a word start with two dots and end with one
#The matrix represent the calculation of the number of possibilities that a character follows the two-character input based on the list of words

for w in words:
    chs = ['.'] + ['.'] + list(w) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        ix1 = stoiTri[ch1 + ch2]
        ix2 = stoi[ch3]
        N[ix1, ix2] += 1

In [31]:
P = (N+1).float()
P /= P.sum(1, keepdims=True)

In [32]:
g = torch.Generator().manual_seed(2147483647)

for i in range(100):
  out = []
  ix = 0
  while True:
    p = P[ix]
    iy = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0: 
        ix = stoiTri['.' + itos[iy]]
    else:
        chs = list(itosTri[ix])
        ix = stoiTri[chs[1] + itos[iy]]
    out.append(itos[iy])
    if iy == 0:
      break
  print(''.join(out))

ce.
bra.
jalius.
rochityharlonimittain.
luwak.
ka.
da.
samiyah.
javer.
gotai.
moriellavojkwuthda.
kaley.
maside.
en.
aviyah.
fobspihiliven.
tahlasuzusfxx.
an.
glhpynn.
isan.
jaridynne.
zam.
der.
jair.
tagaikayshaabelarl.
khysteeven.
abricayharien.
xmvpfkmwmghavaysor.
myson.
laitjaimilaydriseriyen.
kyille.
lahmie.
marah.
ammhgamaxemmy.
asharle.
alcalhy.
jayceasvz.
selane.
nellay.
ra.
adaliyana.
isa.
dougnichrishycero.
all.
jonn.
utstorgious.
ayra.
bekarie.
vikace.
ara.
jayk.
jagh.
crylesterlrklmace.
ro.
prah.
ye.
en.
aidgosell.
mer.
decla.
tie.
khamedahzymareizaymzjvtjuliah.
brik.
alkvsmjamere.
morad.
lie.
mariannanf.
mile.
keonteahaj.
ka.
rena.
mon.
keika.
suynn.
miciawathazhan.
jon.
stie.
kenie.
zakiha.
denovi.
kar.
kas.
try.
azemir.
ret.
ta.
ley.
ke.
sa.
carlorcagatai.
versimikavallin.
skyohaen.
caikeyaderaydew.
aarrecher.
ole.
prisy.
elyn.
jassyn.
abrey.
oah.


In [33]:
log_likelihood = 0.0
n = 0

for w in words:
    chs = ['.'] + ['.'] + list(w) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        ix1 = stoiTri[ch1 + ch2]
        ix2 = stoi[ch3]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

log_likelihood=tensor(-504653.)
nll=tensor(504653.)
2.2119739055633545


In [34]:
xs, ys = [], []

for w in words[:1]:
  chs =  ['.'] + ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoiTri[ch1 + ch2]
    ix2 = stoi[ch3]
    print(ch1, ch2, ch3)
    xs.append(ix1)
    ys.append(ix2)
    
xs = torch.tensor(xs)
ys = torch.tensor(ys)

. . e
. e m
e m m
m m a
m a .


In [35]:
xs

tensor([  0,   5, 148, 364, 352])

In [36]:
ys

tensor([ 5, 13, 13,  1,  0])

In [37]:
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=27**2).float()

In [38]:
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [39]:
xenc.shape

torch.Size([5, 729])

In [41]:
W = torch.rand((729,27))

In [42]:
xenc @ W

tensor([[0.7714, 0.5393, 0.2284, 0.7303, 0.7946, 0.0446, 0.3183, 0.0497, 0.1696,
         0.4956, 0.7268, 0.2263, 0.6220, 0.2805, 0.3995, 0.6871, 0.3330, 0.5705,
         0.3151, 0.4559, 0.4812, 0.0514, 0.6393, 0.5611, 0.2313, 0.1247, 0.3294],
        [0.8417, 0.2635, 0.4251, 0.2493, 0.1266, 0.9735, 0.5118, 0.3605, 0.3309,
         0.2771, 0.8915, 0.2802, 0.1810, 0.4656, 0.4305, 0.2761, 0.4742, 0.1473,
         0.7696, 0.6145, 0.0563, 0.3468, 0.5908, 0.7619, 0.9810, 0.5730, 0.6650],
        [0.0708, 0.1746, 0.2954, 0.7480, 0.3276, 0.8521, 0.7856, 0.6195, 0.9716,
         0.3201, 0.7504, 0.4358, 0.3410, 0.6089, 0.7673, 0.8227, 0.3754, 0.0950,
         0.1181, 0.0362, 0.0481, 0.8381, 0.6602, 0.2637, 0.6150, 0.1423, 0.0935],
        [0.3177, 0.0115, 0.7785, 0.2645, 0.9189, 0.0944, 0.7087, 0.6479, 0.7298,
         0.4166, 0.8008, 0.0854, 0.6418, 0.4600, 0.8456, 0.9442, 0.6465, 0.6790,
         0.0756, 0.4328, 0.9079, 0.3418, 0.1813, 0.1554, 0.1673, 0.0892, 0.6494],
        [0.2690, 0.7751,

In [43]:
xenc.dtype

torch.float32

In [44]:
# randomly initialize 27^2 neurons' weights. each neuron receives 27 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27**2, 27), generator=g)

In [45]:
xenc = F.one_hot(xs, num_classes=27**2).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
# btw: the last 2 lines here are together called a 'softmax'

In [46]:
probs.shape

torch.Size([5, 27])

In [47]:
nlls = torch.zeros(5)
for i in range(5):
  # i-th bigram:
  x = xs[i].item() # input character index
  y = ys[i].item() # label character index
  print('--------')
  print(f'Trigram example {i+1}: {itosTri[x]}{itos[y]} (indexes {x},{y})')
  print('input to the neural net:', x)
  print('output probabilities from the neural net:', probs[i])
  print('label (actual next character):', y)
  p = probs[i, y]
  print('probability assigned by the net to the the correct character:', p.item())
  logp = torch.log(p)
  print('log likelihood:', logp.item())
  nll = -logp
  print('negative log likelihood:', nll.item())
  nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())

--------
Trigram example 1: ..e (indexes 0,5)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label (actual next character): 5
probability assigned by the net to the the correct character: 0.012286253273487091
log likelihood: -4.3992743492126465
negative log likelihood: 4.3992743492126465
--------
Trigram example 2: .em (indexes 5,13)
input to the neural net: 5
output probabilities from the neural net: tensor([0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
        0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
        0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472])
label (actual next character): 13
probability assigned by the net to the the correct charac

In [48]:
# randomly initialize 27 neurons' weights. each neuron receives 27**2 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27**2, 27), generator=g, requires_grad=True)

In [49]:
# forward pass
xenc = F.one_hot(xs, num_classes=27**2).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
loss = -probs[torch.arange(5), ys].log().mean()

In [50]:
print(loss.item())

4.233973503112793


In [51]:
# backward pass
W.grad = None # set to zero the gradient
loss.backward()

In [52]:
W.data += -5 * W.grad

In [53]:
# create the dataset
xs, ys = [], []
for w in words:
  chs = ['.'] +['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoiTri[ch1 + ch2]
    ix2 = stoi[ch3]
    xs.append(ix1)
    ys.append(ix2)


xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27**2, 27), generator=g, requires_grad=True)

number of examples:  228146


In [66]:
# gradient descent
for k in range(100):
  
  # forward pass
  xenc = F.one_hot(xs, num_classes=27**2).float() # input to the network: one-hot encoding
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts, equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean()
  print(loss.item())
  
  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()
  
  # update
  W.data += -100 * W.grad

2.243560552597046
2.243502378463745
2.2434442043304443
2.2433865070343018
2.2433290481567383
2.2432713508605957
2.2432138919830322
2.243156909942627
2.2430999279022217
2.2430434226989746
2.2429871559143066
2.2429306507110596
2.2428743839263916
2.2428183555603027
2.242762565612793
2.2427070140838623
2.2426517009735107
2.242596387863159
2.2425413131713867
2.2424862384796143
2.242431402206421
2.2423768043518066
2.2423226833343506
2.2422683238983154
2.2422142028808594
2.2421603202819824
2.2421066761016846
2.2420530319213867
2.241999626159668
2.2419464588165283
2.2418935298919678
2.2418406009674072
2.241787910461426
2.2417352199554443
2.241683006286621
2.241630792617798
2.2415785789489746
2.2415266036987305
2.2414748668670654
2.2414233684539795
2.2413718700408936
2.2413206100463867
2.241269588470459
2.2412188053131104
2.2411677837371826
2.241117000579834
2.2410666942596436
2.241016387939453
2.2409660816192627
2.2409160137176514
2.240866184234619
2.240816354751587
2.240766763687134
2.2407174

In [67]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
  
  out = []
  ix = 0
  while True:
    
    # ----------
    # BEFORE:
    #p = P[ix]
    # ----------
    # NOW:
    xenc = F.one_hot(torch.tensor([ix]), num_classes=27**2).float()
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    p = counts / counts.sum(1, keepdims=True) # probabilities for next character
    # ----------
    iy = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0: 
        ix = stoiTri['.' + itos[iy]]
    else:
        chs = list(itosTri[ix])
        ix = stoiTri[chs[1] + itos[iy]]
    out.append(itos[iy])
    if iy == 0:
      break
  print(''.join(out))

ce.
bra.
jalius.
rochityharlonimittain.
luwan.
ka.
da.
samiyah.
javer.
gotai.
